INSERT INTO clients (full_name, phone_number, email_address, organization_id, address)
VALUES
('Terry', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '4 Varscliff Place NW, Calgary AB'),
('Brenda', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '30 Varscliff Place NW, Calgary AB'),
('Craig', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '3407 Button Road NW, Calgary AB'),
('Walter', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '3819 Charleswood Drive NW, Calgary AB'),
('Carol', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '24 Brantford Crescent NW, Calgary AB'),
('Paul', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '2004 Crocus Road NW, Calgary AB'),
('Rylea', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '1706 22 Ave NW, Calgary AB'),
('Nelson N', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '1640 20th Ave NW, Calgary AB'),
('Josephine', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '119 15 St NW, Calgary AB'),
('Linda', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '1140 7A Street NW, Calgary AB'),
('Dr Parekh', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', 'Edmonton Trail, Calgary AB'),
('Kam', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '416 10th Ave NE, Calgary AB'),
('Dustin', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '231 4th Ave NE, Calgary AB'),
('Cyrus', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '138 8th Ave NE, Calgary AB'),
('James', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '207 8th Ave NE, Calgary AB'),
('Kevin', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '216 14th Ave NE, Calgary AB'),
('Kathy', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '947 15th Ave NE, Calgary AB'),
('Wendy', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '611 10th St NE, Calgary AB'),
('Immy', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '1420 Child Ave NE, Calgary AB'),
('Azra and Julie', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '701/703 13A St NE, Calgary AB'),
('Jordan', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '305 32nd Ave NE, Calgary AB'),
('Kiki', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '361 Panorama Way NW, Calgary AB'),
('Tahir', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '654 Panatella Blvd NW, Calgary AB'),
('Eddy', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '10 Coventry Cres NE, Calgary AB'),
('Meeta', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '303 Hampstead Way NW, Calgary AB'),
('Samantha', NULL, NULL, 'user_35uYpItCYEItSG6WmiTExQEmT1U', '75 Rockledge Place NW, Calgary AB');
