DROP TABLE IF EXISTS stripe_api_keys CASCADE;

DROP TABLE IF EXISTS yards_marked_cut CASCADE;

DROP TABLE IF EXISTS yards_marked_clear CASCADE;

DROP TABLE IF EXISTS cutting_schedule CASCADE;

DROP TABLE IF EXISTS charges CASCADE;

DROP TABLE IF EXISTS payments CASCADE;

DROP TABLE IF EXISTS accounts CASCADE;

DROP TABLE IF EXISTS clients CASCADE;

DROP TABLE IF EXISTS client_addresses CASCADE;

DROP TABLE IF EXISTS organizations CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS images CASCADE;

DROP TABLE IF EXISTS assignments CASCADE;

DROP TABLE IF EXISTS images_serviced CASCADE;

